Repository KUASE-V3/SMA_T5, pull requests merged in 2025-05, with the labels that each got.

#1 add: ksj_test
  .github/workflows/build.yml
  ksj_test
Labels: good first issue

#9 Sadturtleman
  include/domain/Item.h
  include/domain/ItemManager.h
  include/domain/Payment.h
  include/validator/CardPayValidateAdapter.h
  include/validator/ItemValidator.h
  include/validator/LocalItemValidateAdapter.h
  include/validator/LocalValidator.h
  include/validator/RemoteItemValidateAdapter.h
  include/validator/RemoteValidator.h
  include/validator/Validator.h
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  src/domain/Payment.cpp
  src/validator/CardPayValidateAdapter.cpp
  src/validator/LocalItemValidateAdapter.cpp
  src/validator/RemoteItemValidateAdapter.cpp
Labels: enhancement

#10 validator make and add validator test
  CMakeLists.txt
  include/domain/Item.h
  include/domain/ItemManager.h
  include/domain/Payment.h
  include/validator/ItemValidator.h
  include/validator/ValidatorFactory.h
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  src/domain/Payment.cpp
  src/validator/LocalItemValidateAdapter.cpp
  src/validator/ValidatorFactory.cpp
  tests/domain/test_CLManager.cpp
  tests/domain/test_Item.cpp
  tests/domain/test_ItemManager.cpp
  tests/test_person.cpp
  tests/validator/test_CardPayValidateAdapter.cpp
Labels: enhancement

#11 CLManager order 추가 및 run추가(수정중)
  CMakeLists.txt
  include/domain/CLManager.h
  include/domain/ItemManager.h
  include/domain/Payment.h
  src/domain/CLManager.cpp
  src/domain/ItemManager.cpp
  src/domain/Payment.cpp
  tests/domain/test_CLManager.cpp
  tests/domain/test_Item.cpp
  tests/domain/test_ItemManager.cpp
Labels: enhancement

#12 test code add and coverage 90% up
  CMakeLists.txt
  include/domain/Item.h
  include/domain/ItemManager.h
  src/domain/Item.cpp
  tests/domain/test_Item.cpp
  tests/domain/test_ItemManager.cpp
  tests/domain/test_Payment.cpp
  tests/validator/test_CardPayValidateAdapter.cpp
  tests/validator/test_LocalItemValidateAdapter.cpp
  tests/validator/test_ValidatorFactory.cpp
Labels: enhancement

#13 cmake file update
  CMakeLists.txt
Labels: enhancement

#14 canlocalbuy(), canremotebuy() camelcase로 수정
  tests/domain/test_CLManager.cpp
  tests/domain/test_Payment.cpp
Labels: bug

#15 local에서 pay() 성공시 음료 제공 콘솔 추가
  include/domain/CLManager.h
  include/domain/Item.h
  include/domain/ItemManager.h
  src/domain/CLManager.cpp
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  tests/domain/test_CLManager.cpp
Labels: enhancement

#16 ItemManager increaseStock(), decreaseStock() 추가 및 수량 관련 테스트 수정
  CMakeLists.txt
  include/domain/Item.h
  include/domain/ItemManager.h
  src/domain/CLManager.cpp
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  tests/domain/test_Item.cpp
  tests/domain/test_ItemManager.cpp
  tests/domain/test_Payment.cpp
  tests/validator/test_LocalItemValidateAdapter.cpp
Labels: bug, enhancement

#18 NetworkManger 대략 80%..
  CMakeLists.txt
  include/domain/CLManager.h
  include/domain/CertificationCodeFactory.h
  include/domain/Payment.h
  include/domain/PrepaymentStock.h
  include/network/MessageFactory.h
  include/network/NetworkManager.h
  include/network/json.hpp
  src/domain/CLManager.cpp
  src/domain/CertificationCodeFactory.cpp
  src/domain/Payment.cpp
  src/domain/PrepaymentStock.cpp
  src/main.cpp
  src/network/MessageFactory.cpp
  src/network/NetworkManager.cpp
  tests/domain/test_CertificationCodeFactory.cpp
  tests/domain/test_Payment.cpp
  tests/domain/test_PrepaymentStock.cpp
  tests/network/test_MessageFactory.cpp
Labels: enhancement

#19 feat: NetworkManager 95%...
  CMakeLists.txt
  include/domain/CLManager.h
  include/network/Dvm.h
  include/network/NetworkManager.h
  include/validator/RemoteItemValidateAdapter.h
  src/domain/CLManager.cpp
  src/domain/CertificationCodeFactory.cpp
  src/main.cpp
  src/network/Dvm.cpp
  src/network/MessageFactory.cpp
  src/network/NetworkManager.cpp
  src/validator/RemoteItemValidateAdapter.cpp
  tests/domain/test_Payment.cpp
  tests/network/test_MessageFactory.cpp
Labels: enhancement

#21 test_CLManager에 showItems(), order(), pay()추가 완료
  CMakeLists.txt
  src/person.cpp
  tests/domain/test_CLManager.cpp
Labels: documentation

#23 order 오타 수정
  include/domain/CLManager.h
Labels: enhancement

#24 ItemFactory 7종류 음료만 갖도록 수정
  src/domain/ItemFactory.cpp
Labels: bug

#25 certCode int에서 string으로 변환
  tests/domain/test_Dvm.cpp
Labels: bug

#26 certCode int string 바꾼게 반영이 안되어 있었어
  include/domain/CLManager.h
  include/domain/CertificationCodeFactory.h
  include/domain/Payment.h
  include/domain/PrepaymentStock.h
  include/network/MessageFactory.h
  src/domain/CLManager.cpp
  src/domain/CertificationCodeFactory.cpp
  src/domain/Payment.cpp
  src/domain/PrepaymentStock.cpp
  src/network/MessageFactory.cpp
  src/network/NetworkManager.cpp
  tests/domain/test_CertificationCodeFactory.cpp
  tests/domain/test_Payment.cpp
  tests/domain/test_PrepaymentStock.cpp
  tests/network/test_MessageFactory.cpp
Labels: bug

#74 Add static analysis
  .github/workflows/build_static_analysis.yml
Labels: enhancement

#75 Json 파일로 재고 관리 하도록 변경
  build/T5.json
  build/T6.json
  include/domain/ItemFactory.h
  include/domain/Payment.h
  include/network/Address.h
  include/network/Dvm.h
  include/network/NetworkManager.h
  src/domain/CLManager.cpp
  src/domain/Item.cpp
  src/domain/ItemFactory.cpp
  src/main.cpp
  src/network/Dvm.cpp
  src/network/NetworkManager.cpp
  tests/domain/test_CLManager.cpp
  tests/domain/test_Item.cpp
  tests/domain/test_ItemManager.cpp
Labels: enhancement

#76 readInt 수정 및 getOrder삭제에 따른 전반적 코드 수정
  .gitignore
  include/domain/ItemManager.h
  include/domain/Payment.h
  include/validator/ItemValidator.h
  include/validator/ValidatorFactory.h
  src/domain/CLManager.cpp
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  src/domain/Payment.cpp
  src/main.cpp
  src/validator/LocalItemValidateAdapter.cpp
  src/validator/RemoteItemValidateAdapter.cpp
  src/validator/ValidatorFactory.cpp
  tests/domain/test_Payment.cpp
  tests/domain/test_PrepaymentStock.cpp
  tests/network/test_MessageFactory.cpp
  tests/validator/test_ValidatorFactory.cpp
Labels: bug, enhancement

#77 Payment test code add
  cppcheck_report.sarif
  src/domain/Item.cpp
  src/validator/LocalItemValidateAdapter.cpp
  src/validator/ValidatorFactory.cpp
  tests/domain/test_Payment.cpp
Labels: Test Pass

#79 입출력 수정 및 order수정
  include/domain/CLManager.h
  include/domain/Item.h
  include/domain/ItemManager.h
  include/validator/ItemTypeValidateAdapter.h
  src/domain/CLManager.cpp
  src/domain/Item.cpp
  src/domain/ItemManager.cpp
  src/validator/ItemTypeValidateAdapter.cpp
  src/validator/ValidatorFactory.cpp
  tests/domain/test_CLManager.cpp
Labels: bug, enhancement
